### ISSUE TITLE
Crash problem!! 

### ISSUE THREAD

**Issue by DiScalaG** [Dalarion/Croparia2.0#3]
When you throw any elemental essence from a height above the elementary block with a level 3 ritual table, the game closes and you cannot reload the map.

PS: In the Gui specify which are the materials used to build, since it is not known how to do the ritual for the golems.
I leave the report below

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2020-01-19 12:17:31 BOT
Description: Colliding entity with block

java.lang.NullPointerException
    at com.croparia.mod.Reference.say(Reference.java:45)
    at com.croparia.mod.Rituals.RitualUtils.bad(RitualUtils.java:68)
    at com.croparia.mod.Rituals.SecondRitual.checkRitual(SecondRitual.java:64)
    at com.croparia.mod.Blocks.RitualStand.BlockRitualStandT2.secondRitualCraft(BlockRitualStandT2.java:49)
    at com.croparia.mod.Init.CropariaCraft.RitualCraft2.craft(RitualCraft2.java:23)
    at com.croparia.mod.Blocks.RitualStand.BlockRitualStandT2.onEntityCollision(BlockRitualStandT2.java:33)
    at com.croparia.mod.Blocks.RitualStand.BlockRitualStandT3.onEntityCollision(BlockRitualStandT3.java:38)
    at net.minecraft.entity.Entity.doBlockCollisions(Entity.java:1044)
    at net.minecraft.entity.Entity.move(Entity.java:964)
    at net.minecraft.entity.item.EntityItem.onUpdate(EntityItem.java:122)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zbc000(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block being collided with --
  Block: croparia:ritual_stand_t3
  Block location: World: (231,84,159), Chunk: (at 7,5,15 in 14,9; contains blocks 224,0,144 to 239,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

-- Entity being checked for collision --
  Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
  Entity ID: 6942
  Entity Name: item.item.croparia.elemental_water
  Entity's Exact location: 231.50, 88.00, 159.50
  Entity's Block location: World: (231,88,159), Chunk: (at 7,5,15 in 14,9; contains blocks 224,0,144 to 239,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: -0.01, -0.76, -0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {NoGravity:1b,Motion:[-0.011568297510712344d,-0.761299554291312d,-9.240104735079756E-5d],UUIDLeast:-8329693008705387283L,Health:5s,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[119.126884f,0.0f],Thrower:"DiScala",UpdateBlocked:0b,FallDistance:14.47561f,Item:{id:"croparia:elemental_water",Count:1b,Damage:0s},UUIDMost:-8378130108686383575L,Pos:[231.5d,88.0d,159.5d],PickupDelay:14s,Fire:-1s,Lifespan:6000,Age:24s}

-- Entity being ticked --
  Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
  Entity ID: 6942
  Entity Name: item.item.croparia.elemental_water
  Entity's Exact location: 231.50, 88.00, 159.50
  Entity's Block location: World: (231,88,159), Chunk: (at 7,5,15 in 14,9; contains blocks 224,0,144 to 239,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: -0.01, -0.76, -0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {NoGravity:1b,Motion:[-0.011568297510712344d,-0.761299554291312d,-9.240104735079756E-5d],UUIDLeast:-8329693008705387283L,Health:5s,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[119.126884f,0.0f],Thrower:"DiScala",UpdateBlocked:0b,FallDistance:14.47561f,Item:{id:"croparia:elemental_water",Count:1b,Damage:0s},UUIDMost:-8378130108686383575L,Pos:[231.5d,88.0d,159.5d],PickupDelay:14s,Fire:-1s,Lifespan:6000,Age:24s}

-- Affected level --
  Level name: Summon
  All players: 1 total; [EntityPlayerMP['DiScala'/6941, l='Summon', x=231.81, y=94.74, z=159.38]]
  Chunk stats: ServerChunkCache: 441 Drop: 0
  Level seed: 5714253787509961407
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (172,64,232), Chunk: (at 12,4,8 in 10,14; contains blocks 160,0,224 to 175,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 4184 game time, 4184 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 131455 (now: false), thunder time: 85529 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 412056320 bytes (392 MB) / 704643072 bytes (672 MB) up to 12884901888 bytes (12288 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 20, tallocated: 86
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 7 mods loaded, 7 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID         | Version         | Source                        | Signature |
       |:------ |:---------- |:--------------- |:----------------------------- |:--------- |
       | LCHIJA | minecraft  | 1.12.2          | minecraft.jar                 | None      |
       | LCHIJA | mcp        | 9.42            | minecraft.jar                 | None      |
       | LCHIJA | FML        | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar | None      |
       | LCHIJA | forge      | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar | None      |
       | LCHIJA | croparia   | 2.4             | Croparia-2.5.jar              | None      |
       | LCHIJA | guideapi   | 1.12-2.1.8-63   | Guide-API-1.12-2.1.8-63.jar   | None      |
       | LCHIJA | vanillafix | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar      | None      |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
  Suspected Mods: Croparia (croparia)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['DiScala'/6941, l='Summon', x=231.81, y=94.74, z=159.38]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 2

**Comment by Dalarion** [comment]
Thanks, I'm currently remaking the mod. I will take care about this bug, thank you
